import * as core from '@actions/core'
import type {
  ComprehensiveRelease,
  ReleasePlan,
  VersionType,
} from '@changesets/types'
import {
  type CommitDiffSchema,
  type DiscussionNoteSchema,
  type DiscussionSchema,
  type Gitlab,
  type MergeRequestDiffSchema,
  type MergeRequestNoteSchema,
  type NoteSchema,
  GitbeakerRequestError,
} from '@gitbeaker/rest'
import { humanId } from 'human-id'
import { markdownTable } from 'markdown-table'

import { createApi } from './api.ts'
import { TRUTHY_VALUES } from './constants.js'
import * as context from './context.js'
import { env } from './env.js'
import { getChangedPackages } from './get-changed-packages.js'
import type { LooseString } from './types.js'
import { getCwdInput, getUsername, logGitbeakerError } from './utils.js'

const generatedByBotNote = '__Generated By Changesets GitLab Bot__'

const HTTP_STATUS_NOT_FOUND = 404

const getReleasePlanMessage = (releasePlan: ReleasePlan | null) => {
  if (!releasePlan) {
    return ''
  }

  const publishableReleases = releasePlan.releases.filter(
    (x): x is ComprehensiveRelease & { type: Exclude<VersionType, 'none'> } =>
      x.type !== 'none',
  )

  const table = markdownTable([
    ['Name', 'Type'],
    ...publishableReleases.map(x => [
      x.name,
      {
        major: 'Major',
        minor: 'Minor',
        patch: 'Patch',
      }[x.type],
    ]),
  ])

  return `<details><summary>This MR includes ${
    releasePlan.changesets.length > 0
      ? `changesets to release ${
          // eslint-disable-next-line sonarjs/no-nested-conditional
          publishableReleases.length === 1
            ? '1 package'
            : `${publishableReleases.length} packages`
        }`
      : 'no changesets'
  }</summary>

  ${
    publishableReleases.length > 0
      ? table
      : "When changesets are added to this MR, you'll see the packages that this MR includes changesets for and the associated semver types"
  }

</details>`
}

const customLinks = env.GITLAB_COMMENT_CUSTOM_LINKS?.trim()

const ADD_CHANGESET_URL_PLACEHOLDER_REGEXP = /\{\{\s*addChangesetUrl\s*\}\}/

const getAbsentMessage = (
  commitSha: string,
  addChangesetUrl: string,
  newChangesetTemplateFallback: string,
  releasePlan: ReleasePlan | null,
) => `###  ⚠️  No Changeset found

Latest commit: ${commitSha}

Merging this MR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**

${getReleasePlanMessage(releasePlan)}

${
  customLinks
    ? customLinks.replace(ADD_CHANGESET_URL_PLACEHOLDER_REGEXP, addChangesetUrl)
    : `[Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).

[Click here if you're a maintainer who wants to add a changeset to this MR](${addChangesetUrl})`
}

${newChangesetTemplateFallback}

${generatedByBotNote}
`

const getApproveMessage = (
  commitSha: string,
  addChangesetUrl: string,
  newChangesetTemplateFallback: string,
  releasePlan: ReleasePlan | null,
) => `###  🦋  Changeset detected

Latest commit: ${commitSha}

**The changes in this MR will be included in the next version bump.**

${getReleasePlanMessage(releasePlan)}

${
  customLinks
    ? customLinks.replace(ADD_CHANGESET_URL_PLACEHOLDER_REGEXP, addChangesetUrl)
    : `Not sure what this means? [Click here to learn what changesets are](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).

[Click here if you're a maintainer who wants to add another changeset to this MR](${addChangesetUrl})`
}

${newChangesetTemplateFallback}

${generatedByBotNote}
`

const getNewChangesetTemplate = (
  changedPackages: string[],
  title: string,
) => `---
${changedPackages.map(x => `"${x}": patch`).join('\n')}
---

${title}
`

export const isMrNote = (
  discussionOrNote: DiscussionSchema | MergeRequestNoteSchema,
): discussionOrNote is MergeRequestNoteSchema =>
  'noteable_type' in discussionOrNote &&
  discussionOrNote.noteable_type === 'MergeRequest'

const RANDOM_BOT_NAME_PATTERN = /^((?:project|group)_\d+_bot\w*)_[\da-z]+$/i

const isChangesetBotNote = (
  note: DiscussionNoteSchema | NoteSchema,
  username: string,
  random?: boolean,
) =>
  (note.author.username === username ||
    (random &&
      RANDOM_BOT_NAME_PATTERN.exec(note.author.username)?.[1] === username)) &&
  // We need to ensure the note is generated by us, but we don't have an app bot like GitHub
  // @see https://github.com/apps/changeset-bot
  note.body.includes(generatedByBotNote)

async function getNoteInfo(
  api: Gitlab,
  mrIid: number,
  commentType: LooseString<'discussion'>,
  random?: boolean,
): Promise<{ discussionId: string; noteId: number } | null | undefined>
async function getNoteInfo(
  api: Gitlab,
  mrIid: number,
  commentType: LooseString<'note'>,
  random?: boolean,
): Promise<{ noteId: number } | null | undefined>
async function getNoteInfo(
  api: Gitlab,
  mrIid: number,
  commentType: LooseString<'discussion' | 'note'>,
  random?: boolean,
): Promise<
  | { discussionId: string; noteId: number }
  | { noteId: number }
  | null
  | undefined
> {
  const discussionOrNotes = await (commentType === 'discussion'
    ? api.MergeRequestDiscussions.all(context.projectId, mrIid)
    : api.MergeRequestNotes.all(context.projectId, mrIid))

  const username = await getUsername(api)

  for (const discussionOrNote of discussionOrNotes) {
    if (isMrNote(discussionOrNote)) {
      if (isChangesetBotNote(discussionOrNote, username, random)) {
        return {
          noteId: discussionOrNote.id,
        }
      }
      continue
    }

    if (!discussionOrNote.notes) {
      continue
    }

    const changesetBotNote = discussionOrNote.notes.find(note =>
      isChangesetBotNote(note, username),
    )

    if (changesetBotNote) {
      return {
        discussionId: discussionOrNote.id,
        noteId: changesetBotNote.id,
      }
    }
  }

  /**
   * The `username` used for commenting could be random, if we haven't tested
   * the random `username`, then test it
   *
   * @see https://docs.gitlab.com/ee/development/internal_users.html
   * @see https://github.com/un-ts/changesets-gitlab/issues/145#issuecomment-1860610958
   */
  return random ? null : getNoteInfo(api, mrIid, commentType, true)
}

const hasChangesetBeenAdded = async (
  changedFilesPromise: Promise<CommitDiffSchema[] | MergeRequestDiffSchema[]>,
  changesetDirPrefix: string,
) => {
  const changedFiles = await changedFilesPromise
  return changedFiles.some(file => {
    return (
      file.new_file &&
      file.new_path.startsWith(changesetDirPrefix) &&
      file.new_path.endsWith('.md') &&
      file.new_path !== `${changesetDirPrefix}README.md`
    )
  })
}

export const getCommentStatus = async (
  api: Gitlab = createApi(),
): Promise<{ body: string; hasChangeset: boolean } | undefined> => {
  const mrBranch = env.CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  if (!mrBranch) {
    throw new Error(
      'This command should only be run on a merge request pipeline',
    )
  }

  const {
    CI_MERGE_REQUEST_IID: mrIid,
    GITLAB_ADD_CHANGESET_MESSAGE: commitMessage,
  } = env

  if (mrBranch.startsWith('changeset-release')) {
    return
  }

  const { relative: relativeCwd } = getCwdInput()

  const cwdPrefix = relativeCwd ? `${relativeCwd}/` : ''

  const changesetDirPrefix = `${cwdPrefix}.changeset/`

  let errFromFetchingChangedFiles = ''

  const latestCommitSha = env.CI_MERGE_REQUEST_SOURCE_BRANCH_SHA

  const changedFilesPromise = api.MergeRequests.allDiffs(
    context.projectId,
    mrIid,
  ).catch(async (err: unknown) => {
    if (
      !(err instanceof GitbeakerRequestError) ||
      err.cause?.response.status !== HTTP_STATUS_NOT_FOUND
    ) {
      throw err
    }

    const { changes } = await api.MergeRequests.showChanges(
      context.projectId,
      mrIid,
    )
    return changes
  })

  const packageChangedFiles = changedFilesPromise.then(changedFiles =>
    changedFiles.flatMap(({ new_path }) =>
      new_path.startsWith(cwdPrefix) ? [new_path.slice(cwdPrefix.length)] : [],
    ),
  )

  const [hasChangeset, { changedPackages, releasePlan }] = await Promise.all([
    hasChangesetBeenAdded(changedFilesPromise, changesetDirPrefix),
    getChangedPackages({
      changedFiles: packageChangedFiles,
      cwdPrefix,
    }).catch((err: unknown) => {
      errFromFetchingChangedFiles = `<details><summary>💥 An error occurred when fetching the changed packages and changesets in this MR</summary>\n\n\`\`\`\n${err instanceof Error ? err.message : String(err)}\n\`\`\`\n\n</details>\n`
      return {
        changedPackages: ['@fake-scope/fake-pkg'],
        releasePlan: null,
      }
    }),
  ] as const)

  const newChangesetFileName = `${changesetDirPrefix}${humanId({
    separator: '-',
    capitalize: false,
  })}.md`

  const newChangesetTemplate = getNewChangesetTemplate(
    changedPackages,
    env.CI_MERGE_REQUEST_TITLE,
  )

  const addChangesetUrl = `${env.CI_MERGE_REQUEST_PROJECT_URL}/-/new/${mrBranch}?file_name=${newChangesetFileName}&file=${encodeURIComponent(newChangesetTemplate)}${
    commitMessage ? '&commit_message=' + encodeURIComponent(commitMessage) : ''
  }`

  const newChangesetTemplateFallback = `
If the above link doesn't fill the changeset template file name and content which is [a known regression on GitLab >= 16.11](https://gitlab.com/gitlab-org/gitlab/-/issues/532221), you can copy and paste the following template into ${newChangesetFileName} instead:

\`\`\`yaml
${newChangesetTemplate}
\`\`\`
`.trim()

  const prComment =
    (hasChangeset
      ? getApproveMessage(
          latestCommitSha,
          addChangesetUrl,
          newChangesetTemplateFallback,
          releasePlan,
        )
      : getAbsentMessage(
          latestCommitSha,
          addChangesetUrl,
          newChangesetTemplateFallback,
          releasePlan,
        )) + errFromFetchingChangedFiles

  return { body: prComment, hasChangeset }
}

export const comment = async () => {
  const mrBranch = env.CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  if (!mrBranch) {
    core.warning('[changesets-gitlab:comment] It should only be used on MR')
    return
  }

  if (mrBranch.startsWith('changeset-release')) {
    return
  }

  const { CI_MERGE_REQUEST_IID: mrIid, GITLAB_COMMENT_TYPE: commentType } = env

  const api = createApi()

  try {
    const [status, noteInfo] = await Promise.all([
      getCommentStatus(api),
      getNoteInfo(api, mrIid, commentType),
    ])

    if (!status) {
      return
    }

    const { body: prComment, hasChangeset } = status

    switch (commentType) {
      case 'discussion': {
        if (noteInfo) {
          if (
            hasChangeset &&
            TRUTHY_VALUES.has(env.GITLAB_COMMENT_DISCUSSION_AUTO_RESOLVE || '1')
          ) {
            await api.MergeRequestDiscussions.resolve(
              context.projectId,
              mrIid,
              noteInfo.discussionId,
              true,
            )
          }

          return api.MergeRequestDiscussions.editNote(
            context.projectId,
            mrIid,
            noteInfo.discussionId,
            noteInfo.noteId,
            {
              body: prComment,
            },
          )
        }

        return api.MergeRequestDiscussions.create(
          context.projectId,
          mrIid,
          prComment,
        )
      }
      case 'note': {
        if (noteInfo) {
          return api.MergeRequestNotes.edit(
            context.projectId,
            mrIid,
            noteInfo.noteId,
            { body: prComment },
          )
        }

        return api.MergeRequestNotes.create(context.projectId, mrIid, prComment)
      }
      default: {
        throw new Error(
          `Invalid comment type "${commentType}", should be "discussion" or "note"`,
        )
      }
    }
  } catch (err) {
    await logGitbeakerError(err)
    throw err
  }
}
