import os from 'node:os'
import path from 'node:path'

import * as core from '@actions/core'

import {
  execChangesetsCli,
  getCwdInput,
  getOptionalInput,
  setOutput,
  validateChangesetsCliVersion,
} from './utils.js'

export interface PackCommandOptions {
  /** Path to a publish plan generated by the `select-mode` command */
  publishPlan?: string
  /** Directory to write the packed tarballs to */
  outDir?: string
}

/**
 * GitLab command counterpart of the `changesets/action` `/pack` sub-action.
 * Instead of uploading the packed output as a GitHub artifact, it writes it to
 * a predictable directory that can be shared as a GitLab CI artifact with the
 * `publish` command.
 */
export const pack = async (options: PackCommandOptions = {}): Promise<void> => {
  const { absolute: cwd } = getCwdInput()
  await validateChangesetsCliVersion(cwd)

  const publishPlan = options.publishPlan ?? getOptionalInput('publish-plan')
  const outDir =
    options.outDir ??
    getOptionalInput('out-dir') ??
    path.join(os.tmpdir(), `changeset-pack-${Date.now()}`)

  const args = ['pack', '--out-dir', outDir]
  if (publishPlan) {
    args.push('--from-publish-plan', publishPlan)
  }

  await execChangesetsCli(args, { cwd, env: process.env })

  setOutput('pack-dir', outDir)
  core.info(`Packed packages into ${outDir}`)
}
