import { env } from './env.js'
import { GitLab } from './gitlab.js'
import { getPublishFlags, handlePublishResult } from './main.js'
import { runPublish } from './run.js'
import {
  getBooleanInput,
  getCwdInput,
  getOptionalInput,
  setOutput,
  throwOnRemovedCommitModeInput,
  throwOnRenamedInputs,
  validateChangesetsCliVersion,
} from './utils.js'

export interface PublishCommandOptions {
  /** Directory with packed publish output generated by the `pack` command */
  fromPackDir?: string
}

/**
 * GitLab command counterpart of the `changesets/action` `/publish` sub-action.
 * Accepts the packed output directory generated by the `pack` command instead
 * of a GitHub artifact id.
 */
export const publish = async (
  options: PublishCommandOptions = {},
): Promise<void> => {
  const { absolute: cwd } = getCwdInput()
  await validateChangesetsCliVersion(cwd)
  throwOnRemovedCommitModeInput()
  throwOnRenamedInputs({ publish: 'publish-script' })

  const { GITLAB_TOKEN } = env

  const gitlab = new GitLab({
    gitlabToken: GITLAB_TOKEN,
    cwd,
    pushWithGitCli: getBooleanInput('push-with-git-cli', true),
  })

  const result = await runPublish({
    // `script` matches the upstream `/publish` sub-action, the root action uses
    // `publish-script`; accept both for convenience.
    script: getOptionalInput('script') ?? getOptionalInput('publish-script'),
    gitlab,
    ...getPublishFlags(),
    cwd,
    fromPackDir: options.fromPackDir ?? getOptionalInput('from-pack-dir'),
  })

  if (!result.published) {
    setOutput('published', false)
    setOutput('published-packages', [])
  }

  await handlePublishResult(result, getOptionalInput('published'))
}
